config/routes.rb
Fon::Application.routes.draw do
  resources :cards

  root :to => "game#play"

end

app/models/card.rb
class Card < ActiveRecord::Base
  attr_accessible :name, :shape, :size, :thought_value
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cards }
    end
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
    @card = Card.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @card }
    end
  end

  # GET /cards/new
  # GET /cards/new.json
  def new
    @card = Card.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @card }
    end
  end

  # GET /cards/1/edit
  def edit
    @card = Card.find(params[:id])
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(params[:card])

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render json: @card, status: :created, location: @card }
      else
        format.html { render action: "new" }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cards/1
  # PUT /cards/1.json
  def update
    @card = Card.find(params[:id])

    respond_to do |format|
      if @card.update_attributes(params[:card])
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card = Card.find(params[:id])
    @card.destroy

    respond_to do |format|
      format.html { redirect_to cards_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  def play
    @cards = Card.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/views/cards/_form.html.erb
<%= form_for(@card) do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% @card.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :thought_value %><br />
    <%= f.number_field :thought_value %>
  </div>
  <div class="field">
    <%= f.label :shape %><br />
    <%= f.text_field :shape %>
  </div>
  <div class="field">
    <%= f.label :size %><br />
    <%= f.text_field :size %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing card</h1>

<%= render 'form' %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<h1>Listing cards</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Thought value</th>
    <th>Shape</th>
    <th>Size</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cards.each do |card| %>
  <tr>
    <td><%= card.name %></td>
    <td><%= card.thought_value %></td>
    <td><%= card.shape %></td>
    <td><%= card.size %></td>
    <td><%= link_to 'Show', card %></td>
    <td><%= link_to 'Edit', edit_card_path(card) %></td>
    <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Card', new_card_path %>

app/views/cards/new.html.erb
<h1>New card</h1>

<%= render 'form' %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @card.name %>
</p>

<p>
  <b>Thought value:</b>
  <%= @card.thought_value %>
</p>

<p>
  <b>Shape:</b>
  <%= @card.shape %>
</p>

<p>
  <b>Size:</b>
  <%= @card.size %>
</p>


<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>

app/views/game/play.html.erb
<div id="player">
  <h2> Player </h2>
  <%= label_tag :thought_value %>
  <%= text_field_tag :thought_value, 0 %>
  <h3>Hand</h3>
  <div class="hand">
      
  </div>
</div>


<hr />

<em>hidden from player</em><br>
<%= button_tag "Start Thought Generation", :id=>:generate_thought %><br>
<%= label_tag :thought_generation_rate %>
<%= text_field_tag :thought_generation_rate, 10 %>

<hr />

<div id="vision">
  <h3>Vison</h3>
  <div class="cards">

  </div>
</div>

<hr />

<div id="mind">
  <h3>Mind</h3>
  <div class="cards">
    <% @cards.each do |card| %>
      <div id="mind_card_<%= card.id %>" class="card">
        <%= card.name %>
      </div>
    <% end %>
  </div>
</div>

<%= content_for :head do %>
<script type="text/javascript">
  var mind_cards = <%= raw @cards.to_json %>
  var vision_cards = [];
  var hand_cards = [];
  $(function () {
    init();
  });
</script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fon</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield :head %>
</head>
<body>

<%= yield %>

</body>
</html>